services:
  app:
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://127.0.0.1:5432/matchdb
      SPRING_DATASOURCE_USERNAME: pass
      SPRING_DATASOURCE_PASSWORD: pass

  db:
    image: postgres:15
    container_name: matchdb
    environment:
      POSTGRES_DB: matchdb
      POSTGRES_USER: pass
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"