spring:
  h2:
    console.enabled: true
  datasource:
#    url: jdbc:postgresql://127.0.0.1:5432/matchdb
#    username: pass
#    password: pass
#    driver-class-name: org.postgresql.Driver
    url: jdbc:h2:mem:matchdb
    username: pass
    password: pass
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.H2Dialect

server:
  port: 8080

logging:
  level:
    org:
      springframework: INFO
      hibernate: DEBUG

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true